### ISSUE TITLE
Builds fail, unable to find gitlab-runner-build

### ISSUE THREAD

**Issue by voor** [bitnami/bitnami-docker-gitlab-runner-helper#1]
### Name and Version

bitnami/bitnami-docker-gitlab-runner-helper

### What steps will reproduce the bug?

Run a CI job with the container as the helper image.

Job fails and never starts.

Error message:

```
/bin/bash: line 1: gitlab-runner-build: command not found
```

### What is the expected behavior?

Job should run

### What do you see instead?

Job failed.

### Additional information

The binary is expected to be on the $PATH, and it does not appear to be.

**Comment by voor** [comment]
Weird, it looks like the container gets its `$PATH` from the build container, so the fact it's in the /opt/bitnami folder is totally lost in the helper image.

**Comment by voor** [comment]
I'm not actually able to get past the error in this issue, but I'm seeing another error when I try to manually progress the helper:

```
error: could not lock config file //.gitconfig: Permission denied
```

**Comment by migruiz4** [comment]
Hi @voor, I'm sorry for the late response. 

> Weird, it looks like the container gets its $PATH from the build container, so the fact it's in the /opt/bitnami folder is totally lost in the helper image.

I'm sorry but I don't fully understand what you mean, are you building your own image using `bitnami/gitlab-runner-helper` as base image?

```
$ docker run --rm -it --name gitlab-runner-helper bitnami/gitlab-runner-helper bash
gitlab-runner@8e1cf0554d0d:/$ echo $PATH
/opt/bitnami/common/bin:/opt/bitnami/gitlab-runner-helper/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
gitlab-runner@8e1cf0554d0d:/$ ls /opt/bitnami/gitlab-runner-helper/bin/
gitlab-runner-helper
gitlab-runner@8e1cf0554d0d:/$ gitlab-runner-helper 
NAME:
   gitlab-runner-helper - a GitLab Runner Helper

USAGE:
...
```

In the latest image, I haven't found any issues with the PATH

**Comment by voor** [comment]
We're not running this in docker, it's in containerd inside of a TKG cluster.

**Comment by migruiz4** [comment]
I'm sorry, what I mean is that the base container includes `/opt/bitnami/gitlab-runner-helper/bin` in its environment variable `$PATH`, the gitlab-runner-helper is there and it can be executed.

That would not differ if ran using `docker` or in a Kubernetes pod running in TKG, unless it is being overwritten in an intermediate step, like the pod specs for example.

**Comment by whitlaaa** [comment]
Did you ever find a cause for this issue? I just ran into it, as well, and I'm not seeing anything obvious.

Running `bitnami/gitlab-runner-helper:15.0.0` currently which matches the gitlab-runner on our cluster. Both installed via their respective helm charts.

**Comment by migruiz4** [comment]
Hi @whitlaaa,

I'm sorry but we haven't been able to determine the cause for this issue and it is hard to determine whether it is an issue with the image, gitlab-runner, or the gitlab-runner chart.

The `gitlab-runner` is contained in the image and present in its `PATH` env variable. 
The error `/bin/bash: line 1: gitlab-runner-build: command not found` could mean that maybe the PATH is being overwritten at runtime.
